version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - BACKEND_API_URL=http://0.0.0.0:8001
      - NEXT_PUBLIC_BACKEND_API_URL=http://0.0.0.0:8001
      - NEXT_PUBLIC_API_URL=http://localhost:3000
    restart: unless-stopped
