version: "3"

services:
  street-view:
    image: faiazhossain10/street-view-app:latest
    container_name: street-view-container
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      # For any data that needs to persist
      - ./data:/app/data
