name: Build, Push, and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Get version from package.json
      - name: Get version from package.json
        id: package_version
        run: |
          VERSION=$(node -e "console.log(require('./package.json').version)")
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "TAG=main-${VERSION}" >> $GITHUB_ENV

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: rilusmahmud/street-view-dashboard:${{ env.TAG }}

      # Deploy to production server
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: 202.40.182.162
          port: 4444
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /var/www/html/streetview-dashboard

            # Backup the original docker-compose.yml
            cp docker-compose.yml docker-compose.yml.bak

            # Update the docker-compose.yml file with the new image tag
            sed -i "s|image: rilusmahmud/street-view-dashboard:.*|image: rilusmahmud/street-view-dashboard:${{ env.TAG }}|g" docker-compose.yml

            # Restart the container
            docker compose pull
            docker compose up -d

            echo "Deployment completed successfully!"
